// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Project struct {
	Name *string  `json:"name"`
	Rate *float64 `json:"rate"`
}

type Session struct {
	ID     int64      `json:"id"`
	TaskID int64      `json:"task_id"`
	Start  *time.Time `json:"start"`
	Stop   *time.Time `json:"stop"`
}

type Task struct {
	ID        int64      `json:"id"`
	Name      string     `json:"name"`
	Project   *string    `json:"project"`
	Client    *string    `json:"client"`
	Priority  *string    `json:"priority"`
	Notes     *string    `json:"notes"`
	DueDate   *time.Time `json:"due_date"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}
