// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package db

import (
	"context"
)

const addProject = `-- name: AddProject :one
INSERT OR IGNORE INTO projects (name) VALUES (?) RETURNING name, rate
`

func (q *Queries) AddProject(ctx context.Context, name *string) (Project, error) {
	row := q.db.QueryRowContext(ctx, addProject, name)
	var i Project
	err := row.Scan(&i.Name, &i.Rate)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE name = ?
`

func (q *Queries) DeleteProject(ctx context.Context, name *string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, name)
	return err
}

const getProject = `-- name: GetProject :one
SELECT name, rate FROM projects WHERE name = ?
`

func (q *Queries) GetProject(ctx context.Context, name *string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, name)
	var i Project
	err := row.Scan(&i.Name, &i.Rate)
	return i, err
}

const modifyProject = `-- name: ModifyProject :one
UPDATE projects
SET rate = COALESCE(?1, rate),
    name = ?2
WHERE name = ?3
RETURNING name, rate
`

type ModifyProjectParams struct {
	Rate    *float64 `json:"rate"`
	NewName *string  `json:"new_name"`
	Name    *string  `json:"name"`
}

func (q *Queries) ModifyProject(ctx context.Context, arg ModifyProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, modifyProject, arg.Rate, arg.NewName, arg.Name)
	var i Project
	err := row.Scan(&i.Name, &i.Rate)
	return i, err
}
