// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package db

import (
	"context"
)

const addProject = `-- name: AddProject :exec
INSERT OR IGNORE INTO projects (name) VALUES (?)
`

func (q *Queries) AddProject(ctx context.Context, name *string) error {
	_, err := q.db.ExecContext(ctx, addProject, name)
	return err
}

const getProject = `-- name: GetProject :one
SELECT name FROM projects WHERE name = ?
`

func (q *Queries) GetProject(ctx context.Context, name *string) (*string, error) {
	row := q.db.QueryRowContext(ctx, getProject, name)
	var name_2 *string
	err := row.Scan(&name_2)
	return name_2, err
}
