// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"
	"time"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, task_id, start, stop
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Start,
		&i.Stop,
	)
	return i, err
}

const getTaskSessions = `-- name: GetTaskSessions :many
SELECT id, task_id, start, stop
FROM sessions
WHERE task_id = ?
ORDER BY start DESC
`

func (q *Queries) GetTaskSessions(ctx context.Context, taskID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getTaskSessions, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Start,
			&i.Stop,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modifySession = `-- name: ModifySession :one
UPDATE sessions
SET start = COALESCE(?, start),
  stop = COALESCE(?, stop)
WHERE id = ?
RETURNING id, task_id, start, stop
`

type ModifySessionParams struct {
	Start *time.Time `json:"start"`
	Stop  *time.Time `json:"stop"`
	ID    int64      `json:"id"`
}

func (q *Queries) ModifySession(ctx context.Context, arg ModifySessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, modifySession, arg.Start, arg.Stop, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Start,
		&i.Stop,
	)
	return i, err
}

const start = `-- name: Start :one
INSERT INTO sessions (task_id, start,stop )
VALUES (?, ?, ?)
RETURNING id, task_id, start, stop
`

type StartParams struct {
	TaskID int64      `json:"task_id"`
	Start  *time.Time `json:"start"`
	Stop   *time.Time `json:"stop"`
}

func (q *Queries) Start(ctx context.Context, arg StartParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, start, arg.TaskID, arg.Start, arg.Stop)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Start,
		&i.Stop,
	)
	return i, err
}

const stop = `-- name: Stop :one
UPDATE sessions
SET stop = ?
WHERE id = ?
RETURNING id, task_id, start, stop
`

type StopParams struct {
	Stop *time.Time `json:"stop"`
	ID   int64      `json:"id"`
}

func (q *Queries) Stop(ctx context.Context, arg StopParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, stop, arg.Stop, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Start,
		&i.Stop,
	)
	return i, err
}
