// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package db

import (
	"context"
	"time"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks ("name", "project", "client", "priority", "due_date" )
VALUES(?,?,?,?,?)
RETURNING id, name, project, client, priority, status, notes, due_date, current_session, created_at, updated_at, "foreign"
`

type CreateTaskParams struct {
	Name     string     `json:"name"`
	Project  *string    `json:"project"`
	Client   *string    `json:"client"`
	Priority *string    `json:"priority"`
	DueDate  *time.Time `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Name,
		arg.Project,
		arg.Client,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Project,
		&i.Client,
		&i.Priority,
		&i.Status,
		&i.Notes,
		&i.DueDate,
		&i.CurrentSession,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Foreign,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE
  id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getAllTasks = `-- name: GetAllTasks :many
SELECT
  id, name, project, client, priority, status, notes, due_date, current_session, created_at, updated_at, "foreign"
FROM
  tasks
ORDER BY
  due_date
`

func (q *Queries) GetAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Project,
			&i.Client,
			&i.Priority,
			&i.Status,
			&i.Notes,
			&i.DueDate,
			&i.CurrentSession,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Foreign,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT
  id, name, project, client, priority, status, notes, due_date, current_session, created_at, updated_at, "foreign"
FROM
  tasks
WHERE
  id = ?
LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Project,
		&i.Client,
		&i.Priority,
		&i.Status,
		&i.Notes,
		&i.DueDate,
		&i.CurrentSession,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Foreign,
	)
	return i, err
}

const modifyTask = `-- name: ModifyTask :one
UPDATE tasks
SET
  "name" = COALESCE(?, "name"), 
  "project" = COALESCE(?, "project"),
  "client" = COALESCE(?, "client"),
  "priority" = COALESCE(?, "priority"),
  "due_date" = COALESCE(?, "due_date"),
  "current_session" = COALESCE(?, "current_session")
WHERE
  id = ?
RETURNING id, name, project, client, priority, status, notes, due_date, current_session, created_at, updated_at, "foreign"
`

type ModifyTaskParams struct {
	Name           string     `json:"name"`
	Project        *string    `json:"project"`
	Client         *string    `json:"client"`
	Priority       *string    `json:"priority"`
	DueDate        *time.Time `json:"due_date"`
	CurrentSession *int64     `json:"current_session"`
	ID             int64      `json:"id"`
}

func (q *Queries) ModifyTask(ctx context.Context, arg ModifyTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, modifyTask,
		arg.Name,
		arg.Project,
		arg.Client,
		arg.Priority,
		arg.DueDate,
		arg.CurrentSession,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Project,
		&i.Client,
		&i.Priority,
		&i.Status,
		&i.Notes,
		&i.DueDate,
		&i.CurrentSession,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Foreign,
	)
	return i, err
}
