// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package db

import (
	"context"
	"time"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks ("name", "project", "client", "priority", "due_date" )
VALUES(?,?,?,?,?)
RETURNING id, name, project, client, priority, notes, due_date, created_at, updated_at
`

type CreateTaskParams struct {
	Name     string     `json:"name"`
	Project  *string    `json:"project"`
	Client   *string    `json:"client"`
	Priority *string    `json:"priority"`
	DueDate  *time.Time `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Name,
		arg.Project,
		arg.Client,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Project,
		&i.Client,
		&i.Priority,
		&i.Notes,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllTasks = `-- name: GetAllTasks :many
SELECT
  id, name, project, client, priority, notes, due_date, created_at, updated_at
FROM
  tasks
ORDER BY
  due_date
`

func (q *Queries) GetAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Project,
			&i.Client,
			&i.Priority,
			&i.Notes,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT
  id, name, project, client, priority, notes, due_date, created_at, updated_at
FROM
  tasks
WHERE
  id = ?
LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Project,
		&i.Client,
		&i.Priority,
		&i.Notes,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
